version: '3.8'
services:
  web:
    build: .  # Construye la imagen usando el Dockerfile en el directorio actual
    image: nginx:v1
    ports:
      - "8080:80"
      - "2222:22"
    volumes:
      - ./www:/var/www/html  # Asegúrate de que los archivos se copien en el contenedor
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mysql_data:
